# Generated by Django 3.1.7 on 2021-03-26 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coronanapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='funds',
            field=models.IntegerField(blank=True),
        ),
    ]
