# Generated by Django 3.1.7 on 2021-03-26 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coronanapp', '0002_auto_20210326_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='funds',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
