# Generated by Django 3.1.7 on 2021-04-16 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coronanapp', '0004_bet'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='status',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
